env:
  es6: true
  browser: true

extends:
  - "eslint:recommended"
  - "plugin:promise/recommended"
  - "plugin:import/errors"
  - "plugin:import/warnings"

plugins:
  - "promise"
  - "import"

rules:
  promise/always-return: ["warn"]
  promise/catch-or-return: ["warn"]
  promise/no-return-wrap: ["warn"]

parserOptions:
  ecmaVersion: 6
  sourceType: module

overrides:
  - files:
      - "src/**/*.js"
    rules:
      no-var: ["warn"]
      no-undef: ["warn"]
      prefer-rest-params: ["warn"]
      prefer-const: ["warn"]
      no-unused-vars: ["warn"]
  - files:
      "tests/**/*.js"
    env:
      jest: true
    extends:
      - "plugin:jest/recommended"
      - "plugin:jest/style"
    plugins:
      - jest
