name: Build

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup node environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 14
          cache: 'npm'
          check-latest: true

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Build
        run: npm run build
